version: '3'

services:

  php:
    build: 
      dockerfile: docker/php/Dockerfile
    links:
      - mysql
    depends_on:
      - mysql
    volumes:
      - './src:/var/www/html'  

  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - './src:/var/www/html'
      - './docker/nginx/conf.d:/etc/nginx/conf.d'

  mysql:
    image: mysql:8
    restart: always
    ports:
      - 3306:3306
    env_file:
      - ./src/.env
    volumes:
      - db:/var/lib/mysql

  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin
  #   ports:
  #     - 9090:80
  #   environment:
  #     - PMA_HOST=mysql
  #     - PMA_PORT=3306
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 9191:80
    links:
      - mysql
    env_file:
      - ./src/.env

volumes:
  db: